on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  
name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p zig-out/lib
          echo hello > zig-out/lib/libtest.a
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/lib/libtest.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
