on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  
name: Upload Release Asset

jobs:
  build:
    name: Upload crossterm pre-built library
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        backend: [crossterm]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p zig-out/lib
          echo hello > zig-out/lib/libtest-${{ matrix.platform }}.a

      - name: Create tar.gz
        run: tar -czf zig-out/lib/libtest-${{ matrix.platform }}.tar.gz zig-out/lib/libtest-${{ matrix.platform }}.a
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/lib/libtest-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
